services:
  kestra:
    image: kestra/kestra:latest
    env_file:
      - .env_encoded
    container_name: kestra
    command: server standalone
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      KESTRA_CONFIGURATION: |
        kestra:
          repository:
            type: memory
          queue:
            type: memory
          storage:
            type: local
            local:
              basePath: "/tmp/kestra"

  app:
    build: .
    container_name: elt-app
    volumes:
      - /home/diana/elt-ecommerce/.gcp:/secrets
      - /home/diana/elt-ecommerce/.kaggle:/root/.kaggle
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/elt-ecommerce-tf.json
